name: Build images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-base:
    name: "GHCR: Build and push base"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      hash: ${{ steps.exist.outputs.hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          load: true
          tags: arch-linux

      - name: Check if image exists in GHCR
        id: exist
        run: |
          hash=$(docker run --rm arch-linux pacman -Q | sha256sum | cut -d' ' -f1)
          echo "hash=$hash" >> $GITHUB_OUTPUT
          if docker manifest inspect ghcr.io/its-me/archlinux:$hash > /dev/null 2>&1; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Push image to GHCR
        if: steps.exist.outputs.exist != 'true'
        run: |
          docker tag arch-linux ghcr.io/its-me/archlinux:${{ steps.exist.outputs.hash }}
          docker tag arch-linux ghcr.io/its-me/archlinux:latest
          docker push ghcr.io/its-me/archlinux:${{ steps.exist.outputs.hash }}
          docker push ghcr.io/its-me/archlinux:latest

  push-base-hub:
    name: "Docker Hub: Publish base"
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      REPOSITORY: archlinux
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}

      - name: Check if image exists in Docker Hub
        id: exist
        run: |
          if docker manifest inspect ${{ secrets.HUB_USERNAME }}/$REPOSITORY:${{ needs.build-base.outputs.hash }} > /dev/null 2>&1; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish image to Docker Hub
        if: steps.exist.outputs.exist != 'true'
        run: |
          docker buildx imagetools create \
            --tag ${{ secrets.HUB_USERNAME }}/$REPOSITORY:${{ needs.build-base.outputs.hash }} \
            --tag ${{ secrets.HUB_USERNAME }}/$REPOSITORY:latest \
            ghcr.io/its-me/archlinux:${{ needs.build-base.outputs.hash }}

  push-base-quay:
    name: "Quay: Publish base"
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      REPOSITORY: archlinux
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Quay
        uses: docker/login-action@v4
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Check if image exists in Quay
        id: exist
        env:
          QUAY_NAMESPACE: ${{ secrets.QUAY_USERNAME }}
        run: |
          if docker manifest inspect quay.io/${QUAY_NAMESPACE%%+*}/$REPOSITORY:${{ needs.build-base.outputs.hash }} > /dev/null 2>&1; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish image to Quay
        if: steps.exist.outputs.exist != 'true'
        env:
          QUAY_NAMESPACE: ${{ secrets.QUAY_USERNAME }}
        run: |
          docker buildx imagetools create \
            --tag quay.io/${QUAY_NAMESPACE%%+*}/$REPOSITORY:${{ needs.build-base.outputs.hash }} \
            --tag quay.io/${QUAY_NAMESPACE%%+*}/$REPOSITORY:latest \
            ghcr.io/its-me/archlinux:${{ needs.build-base.outputs.hash }}

  build-builder:
    name: "GHCR: Build and push builder"
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      hash: ${{ steps.exist.outputs.hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.builder
          load: true
          tags: arch-linux-builder

      - name: Check if image exists in GHCR
        id: exist
        run: |
          hash=$(docker run --rm arch-linux-builder pacman -Q | sha256sum | cut -d' ' -f1)
          echo "hash=$hash" >> $GITHUB_OUTPUT
          if docker manifest inspect ghcr.io/its-me/archlinux:builder-$hash > /dev/null 2>&1; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Push image to GHCR
        if: steps.exist.outputs.exist != 'true'
        run: |
          docker tag arch-linux-builder ghcr.io/its-me/archlinux:builder-${{ steps.exist.outputs.hash }}
          docker tag arch-linux-builder ghcr.io/its-me/archlinux:builder
          docker push ghcr.io/its-me/archlinux:builder-${{ steps.exist.outputs.hash }}
          docker push ghcr.io/its-me/archlinux:builder

  push-builder-hub:
    name: "Docker Hub: Publish builder"
    needs: build-builder
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      REPOSITORY: archlinux
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}

      - name: Check if image exists in Docker Hub
        id: exist
        run: |
          if docker manifest inspect ${{ secrets.HUB_USERNAME }}/$REPOSITORY:builder-${{ needs.build-builder.outputs.hash }} > /dev/null 2>&1; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish image to Docker Hub
        if: steps.exist.outputs.exist != 'true'
        run: |
          docker buildx imagetools create \
            --tag ${{ secrets.HUB_USERNAME }}/$REPOSITORY:builder-${{ needs.build-builder.outputs.hash }} \
            --tag ${{ secrets.HUB_USERNAME }}/$REPOSITORY:builder \
            ghcr.io/its-me/archlinux:builder-${{ needs.build-builder.outputs.hash }}

  push-builder-quay:
    name: "Quay: Publish builder"
    needs: build-builder
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      REPOSITORY: archlinux
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Quay
        uses: docker/login-action@v4
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Check if image exists in Quay
        id: exist
        env:
          QUAY_NAMESPACE: ${{ secrets.QUAY_USERNAME }}
        run: |
          if docker manifest inspect quay.io/${QUAY_NAMESPACE%%+*}/$REPOSITORY:builder-${{ needs.build-builder.outputs.hash }} > /dev/null 2>&1; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish image to Quay
        if: steps.exist.outputs.exist != 'true'
        env:
          QUAY_NAMESPACE: ${{ secrets.QUAY_USERNAME }}
        run: |
          docker buildx imagetools create \
            --tag quay.io/${QUAY_NAMESPACE%%+*}/$REPOSITORY:builder-${{ needs.build-builder.outputs.hash }} \
            --tag quay.io/${QUAY_NAMESPACE%%+*}/$REPOSITORY:builder \
            ghcr.io/its-me/archlinux:builder-${{ needs.build-builder.outputs.hash }}
